### ISSUE TITLE
Port name detection error for buses.

### ISSUE THREAD

**Issue by manub23** [TerosTechnology/colibri#160]
Ports declared as 

![code](https://user-images.githubusercontent.com/41229348/101976621-ec170c00-3c6c-11eb-86df-7644db283074.png) 

render as 

![image](https://user-images.githubusercontent.com/41229348/101976608-d43f8800-3c6c-11eb-9c85-08ed16f909d2.png)

in the documentation.

**Comment by smgl9** [comment]
Thank you for the feedback!

That was a bug in older versions but it is supposed to have been solved in the last release.
Can you confirm that you are using TerosHDL 0.0.8?
Have you installed the plugin from the vscode marketplace?

**Comment by manub23** [comment]
@smgl9 Yup. I've tried TerosHDL 0.0.8 on VS Code on both Windows and Linux machines, only to get the same result.

**Comment by smgl9** [comment]
Ok, 

Could you provide us a piece of code (omitting confidential/unnecessary parts) that is failing you? Because we have some test working fine with the same case of use of your screenshot

**Comment by manub23** [comment]
Please find the code [here](https://gist.github.com/manub23/a26d0ccefc9bdd21d1c3bcb3e8b019f3).

**Comment by smgl9** [comment]
I found the bug. It will be solved for the next release.
Thank you!

**Comment by manub23** [comment]
Thank you, @smgl9
