### ISSUE TITLE
`define paramters confuse the diagram generator.

### ISSUE THREAD

**Issue by manub23** [TerosTechnology/colibri#185]
Globally declared parameters (using \`define statements) are parsed weirdly in the documentation generator. 

For example, ``input  [`PORT_WIDTH-1:0] port_name;`` is rendered as

![image](https://user-images.githubusercontent.com/41229348/109923497-e289c700-7ce4-11eb-8068-bc3116ae07a6.png)

where `` `PORT_WIDTH `` is defined elsewhere as `` `define PORT_WIDTH 32 ``.

It seems as if the markdown parser treats the code in-between two backticks `` ` `` as in-line code.

**Comment by smgl9** [comment]
Thank you for reporting it!

We have had very similar issues in the past with some special characters. We wil fix it ;)

**Comment by manub23** [comment]
Thanks, @smgl9

**Comment by smgl9** [comment]
@manub23 In the last release this error has been fixed. 

Feel free to reopen the issue if you have any problem.
