### ISSUE TITLE
Parsing macros in module port declarations

### ISSUE THREAD

**Issue by sjkelly** [TerosTechnology/colibri#239]
Hey all, thanks for this great software package! So far I've had a great experience and got Colibri setup as a github action and integrated with sphinx. I noticed some issues parsing this type of idiom:

```
`define CONDITIONAL_WIRE

module foo(
  `ifdef CONDITIONAL_WIRE
    input in,
  `endif
    input clk
);
...
endmodule
```
Example output:
https://rapcores.org/rapcores/internals.html#spi-state-machine

**Comment by qarlosalberto** [comment]
Thanks! I have fixed the bug, try if now it works.

**Comment by sjkelly** [comment]
Wow, thanks for the fast fix! Link above renders great!

**Comment by qarlosalberto** [comment]
Nice! Feel free to open an issue if you find other bug ;)
